/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Nov 14 23:29:18 EST 2016
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status__c
 */
public enum QueueEvent__c_StatusEnum {

    // Error
    ERROR("Error"),
    // InProcess
    INPROCESS("InProcess"),
    // New
    NEW("New"),
    // Processed
    PROCESSED("Processed");

    final String value;

    private QueueEvent__c_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static QueueEvent__c_StatusEnum fromValue(String value) {
        for (QueueEvent__c_StatusEnum e : QueueEvent__c_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
